server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: making
          uri: http://localhost:8082
          predicates:
            - Path=/coffees/** 
        - id: serving
          uri: http://localhost:8083
          predicates:
            - Path=/servings/** 
        - id: noticeboard
          uri: http://localhost:8084
          predicates:
            - Path= /servingScreens/**
        - id: stock
          uri: http://localhost:8085
          predicates:
            - Path=/beans/** 
        - id: h2db
          uri: http://localhost:8081
          predicates:
            - Path=/test_db/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: h2db
          uri: http://order:8080
          predicates:
            - Path=/test_db/** 
        - id: making
          uri: http://making:8080
          predicates:
            - Path=/coffees/** 
        - id: serving
          uri: http://serving:8080
          predicates:
            - Path=/servings/** 
        - id: noticeboard
          uri: http://noticeboard:8080
          predicates:
            - Path= /servingScreens/**
        - id: stock
          uri: http://stock:8080
          predicates:
            - Path=/beans/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080