apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: user17-order
          image: 879772956301.dkr.ecr.ca-central-1.amazonaws.com/user17-order:v2
          # ports:
          #   - containerPort: 8080
          env:
            - name: GREETING_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-configmaps-demo
                  key: greeter.prefix
          # resources:
          #   requests:
          #     cpu: "200m"
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5